//
// Created by nolasco on 27/06/20.
//

#pragma once

enum class ActionType {
  SKIP_TURN,
  ATTACK_BUILDING,
  ATTACK_CHARACTER,
  ATTACK_STRUCTURE,
  CALL_ENEMY,
  CALL_REINFORCEMENT,
  CHARACTER_POSSESS,
  CHARACTER_SUMMON,
  ITEM_DROP,
  ITEM_PICKPOCKET,
  ITEM_PICKUP,
  ITEM_TRADE,
  ITEM_USE,
  LOCATION_TRAVEL,
  PARTY_CREATE,
  PARTY_DISBAND,
  PARTY_INVITE,
  PARTY_KICK,
  QUEST_ABANDON,
  QUEST_FINISH,
  SHOP_BUY,
  SHOP_SELL,
};
